Add notebooks for import/export detection data
openvinotoolkit/datumaro pull request #1020
Opened 2023-05-24 08:08 UTC by wonjuleee

### Summary

### How to test

### Checklist

- [ ] I have added unit tests to cover my changes.​
- [ ] I have added integration tests to cover my changes.​
- [ ] I have added the description of my changes into [CHANGELOG](https://github.com/openvinotoolkit/datumaro/blob/develop/CHANGELOG.md).​
- [ ] I have updated the [documentation](https://github.com/openvinotoolkit/datumaro/tree/develop/docs) accordingly

### License

- [ ] I submit _my code changes_ under the same [MIT License](https://github.com/openvinotoolkit/datumaro/blob/develop/LICENSE) that covers the project.
  Feel free to contact the maintainers if that's a concern.
- [ ] I have updated the license header for each file (see an example below).

```python
# Copyright (C) 2023 Intel Corporation
#
# SPDX-License-Identifier: MIT
```

2023-05-24 08:14 UTC, JihwanEom approved these changes

2023-05-24 09:09 UTC, cih9088 requested changes
Duplicated files.

2023-05-24 09:09 UTC, cih9088 commented on notebooks/14_import_det_dataset.ipynb
This file seems redundant. I believe it was added into the PR by mistake.

2023-05-25 00:18 UTC, wonjuleee commented on notebooks/14_import_det_dataset.ipynb
Thank you so much. I removed.

2023-05-25 00:19 UTC, cih9088 approved these changes

2023-05-25 00:21 UTC, merged