Add Sampler Plugin
openvinotoolkit/datumaro pull request #115
Opened 2021-02-25 07:20 UTC by harimkang

### Summary

This PR includes
- Adding Sampler plugin that analyzes inference result from the given dataset and selects the ‘best’ and the ‘least amount of’ samples for annotation
- Sampling with entropy based algorithm method
- Supporting CLI for sampler

### How to test

Unittest

`python3 -m unittest -v tests/test_sampler.py`

Testing sampling with dataset (After obtaining the inference result)
> **Notes**: DatasetItem is assumed to always have an annotations, each annotation has a 'score' key in its attributes, and the value of that key must have a probability list for all classes in the data.

```
$ pip install .
$ datum project create -o proj
$ datum source add path <path-to-source> -f <dataset-format> -p proj
$ datum model add -l openvino -p proj -- -d <path-to-model.xml> -w <path-to-model.bin> -i <interpreter-file-path>
$ datum model run -p proj -m <model-name>
$ datum transform -p proj-inference -t sampler -- 
               -algo <algorithm-name>
               -subset_name <subset-name> 
               -sample_name <sampled-set-name> 
               -unsample_name <unsampled-set-name> 
               -m <sampling-method> 
               -k <num-of-samples>
```

### Checklist

- [x] I submit my changes into the `develop` branch
- [ ] I have added description of my changes into [CHANGELOG](https://github.com/openvinotoolkit/datumaro/blob/develop/CHANGELOG.md)
- [ ] I have updated the [documentation](
  https://github.com/openvinotoolkit/datumaro/tree/develop/docs) accordingly
- [x] I have added tests to cover my changes
- [ ] I have [linked related issues](
  https://help.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword))

### License

- [x] I submit _my code changes_ under the same [MIT License](
  https://github.com/opencv/cvat/blob/develop/LICENSE) that covers the project.
  Feel free to contact the maintainers if that's a concern.
- [x] I have updated the license header for each file (see an example below)

```python
# Copyright (C) 2020 Intel Corporation
#
# SPDX-License-Identifier: MIT
```

2021-02-25 13:51 UTC, zhiltsov-max requested changes
Hi, thanks for the contribution!
Please try to keep lines no longer than 80 characters. Consider using enums instead of string constants.

2021-02-25 13:51 UTC, zhiltsov-max commented on datumaro/plugins/sampler/algorithm/entropy.py
> +            elif method in ["mixk", "randtopk"]:
Consider using an enum for instead of string constants.

2021-02-25 13:51 UTC, zhiltsov-max commented on datumaro/plugins/sampler/sampler.py
> +            "-algo",
Consider using only `-a` and `--long-name` variants.

2021-02-25 13:51 UTC, zhiltsov-max commented on datumaro/plugins/sampler/sampler.py
> +        if len(extractor) < 1:
I wouldn't consider this an error.

2021-02-25 13:51 UTC, zhiltsov-max commented on datumaro/plugins/sampler/sampler.py
> +        data_df, infer_df = self._load_inference_from_subset(extractor, subset_name)
Please make the operation to be traversing the input dataset only when `__iter__` is called.

2021-02-25 13:51 UTC, zhiltsov-max commented on datumaro/plugins/sampler/sampler.py
> +            if data.image is None:
Please use `item.has_image`.

2021-02-25 13:51 UTC, zhiltsov-max commented on datumaro/plugins/sampler/sampler.py
> +            width, height = data.image.size
`size` can return `None` in some cases (only `path` provided, but the image file is not available).

2021-02-25 13:51 UTC, zhiltsov-max commented on datumaro/plugins/sampler/sampler.py
> +            from datumaro.plugins.sampler.algorithm.entropy import SampleEntropy
Use relative imports in plugins for intra-plugin imports.

2021-02-26 04:52 UTC, harimkang commented
@zhiltsov-max Thank you for your review. 

I modified the contents and wrote it in commit `'code review update #1' (#f43b64f)`. If you have any questions after checking, please comment.

And CI checking is currently failing because the sampler uses pandas. If there is a guide for the external library, please reply. Currently, it is only added to requirements.txt.

2021-02-26 09:41 UTC, zhiltsov-max commented
Plugin dependencies are considered optional for Datumaro, so putting them to the `requirements.txt` is the right solution. To test you can modify `travis.yml` and add corresponding commands to install plugin dependencies and test it. Make tests in this plugin skipped if they lack a dependency.
The same way we did it for TensorFlow. OpenVINO and Accuracy Checker plugins aren't covered by tests.

2021-02-26 16:51 UTC, zhiltsov-max requested changes

2021-02-26 16:51 UTC, zhiltsov-max commented on datumaro/plugins/sampler/algorithm/entropy.py
> +            msg = "Invalid Data, ImageID not found in data"
I'd suggest to avoid this pattern, because it spreads reader's attention. Just do `raise Exception("some text")`

2021-02-26 16:51 UTC, zhiltsov-max commented on datumaro/plugins/sampler/sampler.py
> +    |s|s%(prog)s -algo entropy -subset_name train -sample_name sample -unsampled_name unsampled -m topk -k 20
Please update this line.

2021-02-26 16:51 UTC, zhiltsov-max commented on datumaro/plugins/sampler/sampler.py
> +            choices=["entropy"],
I'd also introduce an enum for this.

2021-02-26 16:51 UTC, zhiltsov-max commented on datumaro/plugins/sampler/sampler.py
> +        for data in subset:
I suggest calling it `item`.

2021-02-26 16:51 UTC, zhiltsov-max commented on datumaro/plugins/sampler/sampler.py
> +                msg = "Invalid data, the image file is not available"
In the error messages here it would be nice to also print `data.id`.

2021-02-26 16:51 UTC, zhiltsov-max commented on docs/user_manual.md
> +datum transform -t sampler -- \
Please update the example.

2021-02-26 16:51 UTC, zhiltsov-max commented on tests/assets/sampler/inference.csv
> +ImageID,ClassProbability1,ClassProbability2,ClassProbability3,Uncertainty
Can we reduce the example to few lines?

2021-03-02 01:41 UTC, harimkang commented
@zhiltsov-max  Thank you for review.
I modified the contents in commit `code review update #2 (#ccc460f)`.

1. Modify the pattern of exception messages
2. Update multiple examples.
3. Modify the algorithm input parameters String to Enum.
4. Rename Variable (data->item)
5. In case of data image check exception, modify to print data.id together
6. Reduce the number of data in the reference.csv used for the test. (500->30) Correct the test code accordingly and complete the test verification
7. As you advised, modify travis.yml

 If you have any questions, please comment.
Have a nice day :)

2021-03-02 13:51 UTC, merged