Readable COCO and datumaro format for CJK
openvinotoolkit/datumaro pull request #307
Opened 2021-06-22 01:56 UTC by jaesuny

### Summary
Resolve #231.

### How to test

### Checklist

- [x] I submit my changes into the `develop` branch
- [ ] I have added description of my changes into [CHANGELOG](https://github.com/openvinotoolkit/datumaro/blob/develop/CHANGELOG.md)
- [ ] I have updated the [documentation](
  https://github.com/openvinotoolkit/datumaro/tree/develop/docs) accordingly
- [x] I have added tests to cover my changes
- [x] I have [linked related issues](
  https://help.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword)

### License

- [x] I submit _my code changes_ under the same [MIT License](
  https://github.com/openvinotoolkit/datumaro/blob/develop/LICENSE) that covers the project.
  Feel free to contact the maintainers if that's a concern.
- [x] I have updated the license header for each file (see an example below)

```python
# Copyright (C) 2021 Intel Corporation
#
# SPDX-License-Identifier: MIT
```

2021-06-22 06:34 UTC, zhiltsov-max requested changes
Thank you for the PR! Please, add a line (`DATUM_231 = ...`) in `tests/requirements.py` and refer to it in the test annotations.

2021-06-22 07:38 UTC, zhiltsov-max commented on tests/test_coco_format.py
> +    @mark_requirement(Requirements.DATUM_GENERAL_REQ)
```suggestion
    @mark_requirement(Requirements.DATUM_231)
```

2021-06-22 07:38 UTC, zhiltsov-max commented on tests/test_datumaro_format.py
> +    @mark_requirement(Requirements.DATUM_GENERAL_REQ)
```suggestion
    @mark_requirement(Requirements.DATUM_231)
```

2021-06-23 01:40 UTC, jaesuny commented
> Thank you for the PR! Please, add a line (`DATUM_231 = ...`) in `tests/requirements.py` and refer to it in the test annotations.

Updated!

2021-06-23 10:02 UTC, zhiltsov-max commented on datumaro/plugins/coco_format/converter.py
>          with open(path, 'w') as outfile:
```suggestion
        with open(path, 'w', encoding='utf-8') as outfile:
```

2021-06-23 10:03 UTC, zhiltsov-max commented on datumaro/plugins/datumaro_format/converter.py
>          with open(osp.join(save_dir, '%s.json' % self._name), 'w') as f:
```suggestion
        with open(osp.join(save_dir, '%s.json' % self._name), 'w',
                encoding='utf-8') as f:
```

2021-06-23 10:05 UTC, zhiltsov-max commented on datumaro/plugins/coco_format/converter.py
>          with open(path, 'w') as outfile:
```suggestion
        with open(path, 'w', encoding='utf-8') as outfile:
```

2021-06-23 10:28 UTC, zhiltsov-max approved these changes

2021-06-23 10:30 UTC, merged