Add a job to check import formatting using isort
openvinotoolkit/datumaro pull request #333
Opened 2021-07-06 12:44 UTC by IRDonch

### Summary
This allows us to automatically enforce consistent code style when it comes to imports.

I fixed all existing inconsistencies by letting `isort` reformat the entire codebase.

### How to test

N/A

### Checklist

- [x] I submit my changes into the `develop` branch
- [ ] I have added description of my changes into [CHANGELOG](https://github.com/openvinotoolkit/datumaro/blob/develop/CHANGELOG.md)
- [ ] I have updated the [documentation](
  https://github.com/openvinotoolkit/datumaro/tree/develop/docs) accordingly
- [ ] I have added tests to cover my changes
- [ ] I have [linked related issues](
  https://help.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword)

### License

- [x] I submit _my code changes_ under the same [MIT License](
  https://github.com/openvinotoolkit/datumaro/blob/develop/LICENSE) that covers the project.
  Feel free to contact the maintainers if that's a concern.
- [ ] I have updated the license header for each file (see an example below)

```python
# Copyright (C) 2021 Intel Corporation
#
# SPDX-License-Identifier: MIT
```

2021-07-06 17:38 UTC, yasakova-anastasia approved these changes

2021-07-06 18:31 UTC, zhiltsov-max commented on datumaro/cli/__main__.py
> +from .util import CliException, add_subparser
I'm not sure I understand the order it produces. What are the rules for `import` and `from import`?

2021-07-06 18:32 UTC, zhiltsov-max commented on datumaro/cli/commands/merge.py
>  import os.path as osp
I'm not sure I understand the order it produces. What are the rules for `import` and `from import`?

2021-07-06 18:37 UTC, zhiltsov-max commented on .isort.cfg
> +force_sort_within_sections = True
```suggestion
from_first = True
```

2021-07-06 18:38 UTC, zhiltsov-max requested changes
Nice PR!

2021-07-07 09:51 UTC, IRDonch commented on .isort.cfg
> +force_sort_within_sections = True
OK, updated.

2021-07-07 12:29 UTC, zhiltsov-max approved these changes

2021-07-07 12:29 UTC, merged