[WIP] Dataset meta file for some formats
openvinotoolkit/datumaro pull request #575
Opened 2021-12-06 09:21 UTC by yasakova-anastasia

### Summary

Added meta file support in following formats:
- CamVid
- KITTI Raw
- LabelMe
- Mapillary Vistas
- MOT
- MOTS
- Open Images
- VggFace2

### How to test

### Checklist

- [ ] I submit my changes into the `develop` branch
- [ ] I have added description of my changes into [CHANGELOG](https://github.com/openvinotoolkit/datumaro/blob/develop/CHANGELOG.md)
- [ ] I have updated the [documentation](
  https://github.com/openvinotoolkit/datumaro/tree/develop/docs) accordingly
- [ ] I have added tests to cover my changes
- [ ] I have [linked related issues](
  https://help.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword)

### License

- [ ] I submit _my code changes_ under the same [MIT License](
  https://github.com/openvinotoolkit/datumaro/blob/develop/LICENSE) that covers the project.
  Feel free to contact the maintainers if that's a concern.
- [ ] I have updated the license header for each file (see an example below)

```python
# Copyright (C) 2021 Intel Corporation
#
# SPDX-License-Identifier: MIT
```

2021-12-08 17:46 UTC, IRDonch requested changes

2021-12-08 17:46 UTC, IRDonch commented on datumaro/plugins/labelme_format.py
> +                from_iterable(parse_meta_file(dataset_root).keys()) }
```suggestion
                    from_iterable(parse_meta_file(dataset_root).keys()) }
```

2021-12-08 17:46 UTC, IRDonch commented on datumaro/plugins/mot_format.py
> +           self._save_meta_file(self._save_dir)
```suggestion
            self._save_meta_file(self._save_dir)
```

2021-12-08 17:46 UTC, IRDonch commented on datumaro/plugins/vgg_face2_format.py
> +            path = osp.join(self._dataset_dir, VggFace2Path.LABELS_FILE)
Duplicate `osp.join` call.

2021-12-08 17:46 UTC, IRDonch commented on datumaro/plugins/vgg_face2_format.py
> +           self._save_meta_file(save_dir)
```suggestion
            self._save_meta_file(save_dir)
```

2021-12-09 08:48 UTC, yasakova-anastasia commented
@IRDonch, I fixed this points.

2021-12-09 12:26 UTC, IRDonch approved these changes

2021-12-09 12:26 UTC, merged