Add VGGFace2 format support
openvinotoolkit/datumaro pull request #69
Opened 2020-12-23 11:56 UTC by yasakova-anastasia

### Summary

Added support for VGGFace2 format

### How to test

### Checklist

- [ ] I submit my changes into the `develop` branch
- [ ] I have added description of my changes into [CHANGELOG](https://github.com/openvinotoolkit/datumaro/blob/develop/CHANGELOG.md)
- [ ] I have updated the [documentation](
  https://github.com/openvinotoolkit/datumaro/tree/develop/docs) accordingly
- [ ] I have added tests to cover my changes
- [ ] I have [linked related issues](
  https://help.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword))

### License

- [ ] I submit _my code changes_ under the same [MIT License](
  https://github.com/opencv/cvat/blob/develop/LICENSE) that covers the project.
  Feel free to contact the maintainers if that's a concern.
- [ ] I have updated the license header for each file (see an example below)

```python
# Copyright (C) 2020 Intel Corporation
#
# SPDX-License-Identifier: MIT
```

2020-12-23 15:52 UTC, zhiltsov-max requested changes

2020-12-23 15:52 UTC, zhiltsov-max commented on datumaro/plugins/vgg_face2_format.py
> +            raise Exception("Can't read annotation file '%s'" % path)
I suggest changing the message, or adding `Expected a '.csv' annotation file`.

2020-12-23 15:52 UTC, zhiltsov-max commented on datumaro/plugins/vgg_face2_format.py
> +        match = re.fullmatch(r'loose_landmark_\S+', subset)
I feel like we need to use the constant above here. How about `startswith()`?

2020-12-23 15:52 UTC, zhiltsov-max commented on datumaro/plugins/vgg_face2_format.py
> +            if len([p for p in row if row[p] == '']) == 0:
There is a visibility flag for missing points. Also we need to check if the number of points is different from 5.

2020-12-24 15:31 UTC, zhiltsov-max approved these changes
As I understood from the dataset description, there are also [attributes](https://github.com/ox-vgg/vgg_face2/tree/master/attributes), face direction and age properties somewhere.

2020-12-24 16:21 UTC, yasakova-anastasia commented
Yes, I think it is. But the official website of this dataset is not available and I don’t know how to get more information.

2020-12-25 08:40 UTC, merged