Support full encryption/decryption functionalities for image datasets.
openvinotoolkit/datumaro pull request #831
Opened 2023-02-28 07:02 UTC by vinnamkim

### Summary

### How to test

### Checklist

- [ ] I submit my changes into the `develop` branch
- [ ] I have added description of my changes into [CHANGELOG](https://github.com/openvinotoolkit/datumaro/blob/develop/CHANGELOG.md)
- [ ] I have updated the [documentation](
  https://github.com/openvinotoolkit/datumaro/tree/develop/docs) accordingly
- [ ] I have added tests to cover my changes
- [ ] I have [linked related issues](
  https://help.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword)

### License

- [ ] I submit _my code changes_ under the same [MIT License](
  https://github.com/openvinotoolkit/datumaro/blob/develop/LICENSE) that covers the project.
  Feel free to contact the maintainers if that's a concern.
- [ ] I have updated the license header for each file (see an example below)

```python
# Copyright (C) 2023 Intel Corporation
#
# SPDX-License-Identifier: MIT
```

2023-03-10 01:12 UTC, wonjuleee requested changes
Please hold this until reviewing cryptography-related security tasks.

2023-03-17 06:05 UTC, wonjuleee approved these changes, later dismissed
The codes look great to me. 
But, let's do below in the future
- separate an option for media encryption
- reduce the encryption/decryption overhead
- provide jupyternotebook or cli tutorial for the practical usage of data encryption

2023-03-17 07:21 UTC, vinnamkim commented
> The codes look great to me. But, let's do below in the future

I made tickets to resolve your issues
> * separate an option for media encryption
- Ticket no. 106290
> * reduce the encryption/decryption overhead
- Ticket no. 105335
> * provide jupyter notebook or cli tutorial for the practical usage of data encryption
- Ticket no. 105333

2023-03-17 07:43 UTC, wonjuleee approved these changes

2023-03-17 07:45 UTC, merged